import streamlit as st


@st.cache_resource(show_spinner=False)
def provide_more_stopwords(language: str) -> list[str]:
    """
    Returns a list of more stopwords which are not in nltk stopwords.
    A new language and a list of your preferred stopwords can be added to this dictionary
    """
    stopwords = {
        "english": [
            'doi', 'also', 'often', 'see', 'could', 'seem', 'others', 'us', 'https', 'www', 'said', 'end',
            'next', 'likely', 'whether', 'another', 'going', 'go', 'without', 'would', 'doing', 'someone',
            'one', 'thing', 'two', 'no', 'Whenever', 'every', 'something', 'somethings', 'things', 'used',
            'com', 'However', 'rather', 'still', 'put', 'que', 'p', 'la', 'de', 'pp', 'Thus', 'ed', 'en',
            'vol', 'th', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p',
            'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I',
            'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'seems',
            'come', 'Come', 'whenever', 'three', 'yet', 'way', 'TXT', 'txt', 'pc', 'either', 'ing', 'else',
            'ever', 'therefore', 'le', 'ly', 'es', 'er', 'oin', 'sa', 'ent', 'od', 'although', 'ye', 'thy',
            'Fo', 'though', 'ng', 'hath', 'thee', 'unto', 'whatever', 'Thou', '0o', '0s', '3a', '3b', '3d',
            '6b', '6o', 'a1', 'a2', 'a3', 'a4', 'ab', 'able', 'abst', 'ac', 'according', 'accordingly',
            'actually', 'ad', 'added', 'adj', 'ae', 'af', 'afterwards', 'ag', 'ah', "ain't", 'aj', 'al',
            'allow', 'allows', 'almost', 'along', 'already', 'among', 'amongst', 'amoungst', 'anybody',
            'anyhow', 'anymore', 'anyone', 'anything', 'anyway', 'anyways', 'anywhere', 'ao', 'ap', 'apart',
            'apparently', 'approximately', 'ar', 'arent', 'arise', 'around', "a's", 'aside', 'ask', 'asking',
            'au', 'av', 'aw', 'away', 'awfully', 'ax', 'ay', 'az', 'b1', 'b2',  'b3', 'ba', 'back', 'bc',
            'bd', 'became', 'become', 'becomes', 'becoming', 'beforehand', 'bl', 'bn', 'beginning',
            'beginnings', 'begins', 'behind', 'beside', 'besides', 'bi', 'biol', 'bj', 'bk', 'bl', 'bn',
            'bottom', 'bp', 'br', 'brief', 'briefly', 'bs', 'bt', 'bu', 'bx', 'c1', 'c2', 'c3', 'ca', 'came',
            'cannot', 'cant', "can't", 'cause', 'causes', 'cc', 'cd', 'ce', 'cf', 'cg', 'ch', 'ci', 'cit',
            'cj', 'cl', 'clearly', 'cm', "c'mon", 'cn', 'co', 'comes', 'con', 'couldnt', 'course', 'cp',
            'cq', 'cr', 'cry', 'cs', "c's", 'ct', 'cu', 'currently', 'cv', 'cx', 'cy', 'cz', 'd2', 'da',
            'dc', 'dd', 'definitely', 'described', 'despite', 'df', 'di', 'dj', 'dk', 'dl', "doesn't", 'dp',
            'dr', 'ds', 'dt', 'du', 'due', 'dx', 'dy', 'e2', 'e3', 'ea', 'ec', 'edu', 'ee', 'ef', 'eg', 'ei',
            'eight', 'eighty', 'ej', 'el', 'eleven', 'elsewhere', 'em', 'empty', 'ending', 'entirely', 'eo',
            'ep', 'eq', 'especially', 'est', 'et', 'et-al', 'etc', 'eu', 'ev', 'even', 'everybody', 'everyone',
            'everything', 'everywhere', 'ex', 'exactly', 'example', 'except', 'ey', 'f2', 'fa', 'far', 'fc',
            'ff', 'fi', 'fifteen', 'fifth', 'fify', 'fill', 'find', 'first', 'five', 'fix', 'fj', 'fl', 'fn',
            'fo', 'followed', 'following', 'follows', 'forth', 'forty', 'found', 'four', 'fr', 'front', 'fs',
            'ft', 'fu', 'full', 'furthermore', 'fy', 'ga', 'gave', 'ge', 'gets', 'getting', 'gi', 'given',
            'gives', 'giving', 'gj', 'gl', 'goes', 'gone', 'got', 'gotten', 'gr', 'greetings', 'gs', 'howbeit',
            'gy', 'h2', 'h3', 'hasnt', 'hed', "he'd", "he'll", 'hello', 'help', 'hence', 'hereafter', 'hereby',
            'herein', 'heres', "here's", 'hereupon', 'hes', "he's", 'hh', 'hi', 'hid', 'hither', 'hj', 'ho',
            'however', "how's", 'hr', 'hs', 'http', 'hu', 'hundred', 'hy', 'i2', 'i3', 'i4', 'i6', 'i7', 'i8',
            'ia', 'ib', 'ibid', 'ic', 'id', "i'd", 'ie', 'ig', 'ignored', 'ih', 'ii', 'ij', 'il', "i'll", 'im',
            "i'm", 'inasmuch', 'inc', 'indeed', 'index', 'inner', 'insofar', 'instead', 'io', 'ip', 'iq', 'ir',
            'itd', "it'd", "it'll", 'iv', "i've", 'ix', 'iy', 'iz', 'jj', 'jr', 'js', 'jt', 'ju', 'ke', 'keeps',
            'kept', 'kg', 'kj', 'km', 'knows', 'ko', 'l2', 'largely', 'last', 'lately', 'later', 'latter', 'liked',
            'latterly', 'lb', 'lc', 'least', 'les', 'less', 'lest', 'let', 'lets', "let's", 'lf', 'like', 'line',
            'little', 'lj', 'ln', 'lo', 'look', 'looking', 'looks', 'los', 'lr', 'ls', 'lt', 'ltd', 'm2', 'made',
            'mainly', 'make', 'makes', 'many', 'may', 'maybe', 'mean', 'means', 'meantime', 'meanwhile', 'asked',

            'merely', 'mg', 'might', 'mill', 'mine', 'miss', 'ml', 'mn', 'mo', 'moreover', 'mostly', 'ne',
            'mr', 'mrs', 'ms', 'mt', 'mu', 'much', 'must', 'n2', 'na', 'name', 'namely', 'nay', 'oo', 'needs',
            'near', 'nearly', 'necessarily', 'neither', 'never', 'nevertheless', 'noone', 'qu', 'qj', 'py',
            'ni', 'nine', 'ninety', 'nj', 'nl', 'nn', 'nobody', 'non', 'none', 'nonetheless', 'nc', 'nd',
            'nos', 'noted', 'nothing', 'nowhere', 'nr', 'ns', 'nt', 'ny', 'oa', 'ob', 'obtained', 'normally',
            'obviously', 'oc', 'og', 'oh', 'oi', 'oj', 'ok', 'okay', 'ol', 'old', 'om', 'omitted', 'ones', 'ox',
            'op', 'oq', 'ord', 'os', 'ot', 'otherwise', 'ou', 'ought', 'outside', 'overall', 'ow', 'owing',
            'p1', 'p2', 'p3', 'page', 'pagecount', 'pages', 'par', 'part', 'particular', 'particularly', 'pas',
            'pd', 'pe', 'per', 'perhaps', 'pf', 'ph', 'pi', 'pj', 'pk', 'pl', 'placed', 'plus', 'pm', 'pn',
            'po', 'possibly', 'potentially', 'pq', 'pr', 'predominantly', 'presumably', 'oz', 'past', 'onto',
            'previously', 'primarily', 'probably', 'promptly', 'provides', 'ps', 'pt', 'pu', "she'd", "she'll",
            'quickly', 'qv', 'r2', 'ra', 'ran', 'rc', 'rd', 'readily', 'really', 'reasonably', 't3', 'take',
            'recently', 'ref', 'refs', 'regarding', 'regardless', 'regards', 'related', 'relatively', 't2',
            'research-articl', 'respectively', 'resulted', 'resulting', 'rf', 'rh', 'ri', 'rj', 'til', 'tip',
            'rl', 'rm', 'rn', 'ro', 'rq', 'rr', 'rs', 'rt', 'ru', 'rv', 'ry', 's2', 'saw', 'say', 'saying',
            'says', 'sc', 'sd', 'se', 'sec', 'second', 'secondly', 'seeing', 'seemed', 'seeming', 'seen',
            'self', 'selves', 'sent', 'seriously', 'seven', 'several', 'sf', 'shall', 'shed', 'somebody',
            'shes', 'showed', 'shown', 'showns', 'shows', 'si', 'side', 'significantly', 'similar', 'zero',
            'similarly', 'since', 'six', 'sixty', 'sj', 'sl', 'slightly', 'sm', 'sn', 'somehow', 'use',
            'somethan', 'sometime', 'sometimes', 'somewhat', 'somewhere', 'soon', 'sp', 'specifically',
            'specifying', 'sq', 'sr', 'ss', 'st', 'stop', 'strongly', 'sub', 'substantially', 'thats',
            'successfully', 'sufficiently', 'sup', 'sure', 'sy', 'sz', 't1', "there'll", 'thereof', 'yt',
            'taken', 'taking', 'tb', 'tc', 'td', 'te', 'tell', 'ten', 'tends', 'tf', 'thank', 'thanx',
            "that's", "that've", 'thence', 'thereafter', 'thereby', 'thered', 'therein', "where's", 'ui',
            'therere', 'theres', "there's", 'thereto', 'thereupon', "there've", 'theyd', 'wasnt', 'wed',
            "they'd", "they'll", 'theyre', "they're", "they've", 'thickv', 'thin', 'third', 'thorough',
            'thoroughly', 'thou', 'thoughh', 'throug', 'throughout', 'thru', 'thus', 'ti', 'wants',
            'tj', 'tl', 'tm', 'tn', 'took', 'top', 'tp', 'tq', 'tr', 'tried', 'tries', 'u201d', 'ue',
            'truly', 'trying', 'ts', "t's", 'tt', 'tv', 'twelve', 'twenty', 'twice', 'tx', 'zi', 'zz',
            'uj', 'uk', 'um', 'un', 'unfortunately', 'unless', 'unlike', 'unlikely', 'uo', 'upon', 'ups',
            'usefully', 'usefulness', 'uses', 'using', 'usually', 'ut', 'va', 'various', 'vd', 'via', 'ur',
            'viz', 'vj', 'vo', 'vols', 'volumtype', 'vq', 'vs', 'vt', 'vu', 'wa', 'want', 'wheres', 'whats',
            "we'd", 'welcome', 'well', "we'll", 'well-b', 'went', "we're", 'werent', "we've", "what'll",
            "what's", 'whence', "when's", 'whereafter', 'whereas', 'whereby', 'wherein', 'wont', 'words',
            'whereupon', 'wherever', 'whim', 'whither', 'whod', 'whoever', 'whole', "who'll", 'whomever',
            "who's", 'whose', "why's", 'wi', 'widely', 'willing', 'wish', 'within', 'wo', 'xt', 'xv', 'xx',
            'wouldnt', 'x1', 'x2', 'x3', 'xf', 'xi', 'xj', 'xk', 'xl', 'xn', 'xo', 'xs', 'whos', 'specified',
            'y2', 'yes', 'yj', 'yl', 'youd', 'youre', 'yr', 'ys',
        ],
        "spanish": [
            'solo', 'somos', 'tan', 'aun', 'mismo', 'misma', 'mas', 'si', 'sere', 'veras', 'aqui', 'ser',
            'veía', 'miró', 'dos', 'casi', 'aún', 'tal', 'pues', 'ambos', 'cada', 'ahí', 'allá', 'hacía',
            'hacia', 'vio', 'ir', 'paso', 'Además', 'tomó', 'iba', 'pasó', 'así', 'después', 'aunque',
            'debía', 'dejo', 'cosa', 'cómo', 'tipo', 'va', 'par', 'punto', 'voy', 'ver', 'rato', 'vez',
            'dio', 'sido', 'vas', 'aquella', 'debía', 'veces', 'abrió', 'dejó', 'podía', 'sabe', 'cosas',
            'podría', 'aquello', 'sabes', 'sabía', 'aquí', 'aquel', 'entonces', 'hecho', 'hace', 'hizo',
            'B', 'hacer', 'Ah', 'debe', 've', 'unas', 'vamos', 'haber', 'allí', 'dicho', 'mientras', 'quién',
            'echo', 'algún', 'dijo', 'dice', 'vi', 'digo', 'toda', 'todo', 'veo', 'puedo', 'dije', 'sola',
            'solo', 'solas', 'solos', 'usted', 'sólo', 'dónde', 'echó', 'tres', 'cuatro', 'sinco', 'seis',
            'ocho', 'nueve', 'in', 'n', 'c', 'ello', 'ta', 'tal', 'ba', 'h', 'a', 'b', 'd', 'e', 'f', 'g',
            'h', 'i', 'j', 'k', 'l', 'm', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'as', 'etc',
            'au', 'be', 'ne', 're', 'ra', 'na', 'jo', 'tra', 'ca', 'usté', 'sa', 'co', 'ro', 'des', 'lado',
            'pa', 'an', 'to', 'todas', 'todos', 'iban', 'vió', 'tras', 'dar', 'Jos', 'fué', 'ésta', 'nte',
            'éste', 'of', 'is', 'there', 'the', 'éstos', 'siete', 'so', 'Do', 'do', 'and', 'this', 'those',
            'merely', 'mg', 'might', 'mill', 'million', 'mine', 'ml', 'mn', 'mo', 'moreover', 'mostly',
            'move', 'ms', 'mt', 'mu', 'much', 'must', 'n2', 'na', 'name', 'namely', 'nay', 'nc', 'nd', 'ne',
            'near', 'nearly', 'necessarily', 'need', 'needs', 'neither', 'never', 'nevertheless', 'new', 'ni',
            'nine', 'ninety', 'nj', 'nl', 'nn', 'nobody', 'non', 'none', 'nonetheless', 'noone', 'normally',
            'nos', 'noted', 'nothing', 'actualmente', 'adelante', 'además', 'afirmó', 'agregó', 'ahora', 'alguna',
            'alguno', 'alrededor', 'ampleamos', 'anterior', 'apenas', 'aproximadamente', 'aquellas', 'aquellos',
            'arriba', 'aseguró', 'atras', 'ayer', 'añadió', 'bajo', 'bastante', 'bien', 'buen', 'buena', 'buenas',
            'bueno', 'buenos', 'cerca', 'cierta', 'ciertas', 'cierto', 'ciertos', 'cinco', 'comentó', 'conocer',
            'conseguimos', 'conseguir', 'considera', 'consideró', 'consigo', 'consigue', 'consiguen', 'consigues',
            'creo', 'cuales', 'cualquier', 'cuanto', 'cuenta', 'da', 'dado', 'dan', 'deben', 'debido', 'decir',
            'demás', 'dentro', 'dicen', 'dieron', 'diferente', 'diferentes', 'dijeron', 'ejemplo', 'embargo',
            'empleais', 'emplean', 'emplear', 'empleas', 'empleo', 'encima', 'encuentra', 'eramos', 'estad',
            'estais', 'estan', 'ex', 'existe', 'existen', 'explicó', 'expresó', 'fin', 'gran', 'grandes', 'gueno',
            'haceis', 'hacemos', 'hacen', 'hacerlo', 'haces', 'haciendo', 'hago', 'hicieron', 'hoy', 'igual',
            'incluso', 'indicó', 'informó', 'intenta', 'intentais', 'intentamos', 'intentan', 'intentar', 'éstas',
            'intentas', 'intentó', 'intento', 'junto', 'largo', 'llegó', 'lleva', 'llevar', 'luego', 'lugar',
            'manera', 'manifestó', 'mayor', 'mediante', 'mejor', 'mencionó', 'menos', 'mio', 'mismas', 'mismos',
            'modo', 'momento', 'mucha', 'muchas', 'nadie', 'ninguna', 'ningunas', 'ninguno', 'ningunos', 'ningún',
            'nueva', 'nuevas', 'nuevos', 'nunca', 'parece', 'parte', 'partir', 'pasada', 'pasado', 'podriamos',
            'pesar', 'poca', 'pocas', 'pocos', 'podeis', 'podemos', 'poder', 'podria', 'podriais', 'uso', 'vais',
            'podrian', 'podrias', 'podrá', 'podrán', 'podrían', 'poner', 'por qué', 'posible', 'primer', 'primera',
            'primero', 'primeros', 'principalmente', 'propia', 'propias', 'propio', 'propios', 'próximo', 'próximos',
            'pudo', 'pueda', 'puede', 'pueden', 'quedó', 'queremos', 'quiere', 'realizado', 'realizar', 'realizó',
            'respecto', 'sabeis', 'sabemos', 'saben', 'saber', 'segunda', 'segundo', 'según', 'señaló', 'siempre',
            'siendo', 'sigue', 'siguiente', 'sino', 'solamente', 'tampoco', 'teneis', 'tener', 'tercera', 'ti',
            'tiempo', 'todavía', 'total', 'trabaja', 'trabajais', 'trabajamos', 'trabajan', 'trabajar', 'trabajas',
            'trabajo', 'trata', 'través', 'ultimo', 'usa', 'usais', 'usamos', 'usan', 'usar', 'usas', 'último',
            'valor', 'van', 'varias', 'varios', 'vaya', 'verdad', 'verdadera', 'verdadero', 'última', 'últimas',
            'últimos'
        ],
        "german": [
            'beim', 'P', 'jedoch', 'ging', 'darauf', 'c', 'deren', 'kam', 'm',
        ],
        "french": [
            'a', 'alors', 'aucun', 'aussi', 'autre', 'avant', 'avoir', 'bon', 'car', 'ceci', 'cela', 'cet', 'cette',
            'ceux', 'chaque', 'ci', 'comme', 'comment', 'dedans', 'dehors', 'depuis', 'deux', 'devoir', 'devrait',
            'devrez', 'devriez', 'devrions', 'devrons', 'devront', 'dois', 'doit', 'donc', 'dos', 'droite', 'dès',
            'début', 'dù', 'elles', 'encore', 'faire', 'fais', 'faisez', 'fait', 'faites', 'fois', 'font', 'force',
            'haut', 'hors', 'ici', 'juste', 'leurs', 'là', 'maintenant', 'moins', 'mot', 'ni', 'nom', 'nommé', 'nommée',
            'nommés', 'nouveau', 'nouveaux', 'où', 'parce', 'parole', 'personne', 'personnes', 'peu', 'peut', 'plupart',
            'pourquoi', 'quand', 'quel', 'quelle', 'quelles', 'quels', 'sans', 'seulement', 'si', 'sien', 'soi', 'sous',
            'sujet', 'tandis', 'tellement', 'tels', 'tous', 'tout', 'trop', 'très', 'valeur', 'voient', 'vois', 'voit',
            'vont', 'vu', 'ça', 'état', 'être'
        ],
        "italian": [
            'adesso', 'allora', 'altre', 'altri', 'altro', 'ancora', 'avere', 'dentro', 'ecco', 'fare', 'fino', 'fra',
            'giù', 'me', 'no', 'però', 'pochi', 'poco', 'qua', 'quasi', 'qui', 'quindi', 'senza', 'sopra', 'sotto',
            'stare', 'stesso', 'te', 'vai'
        ],
        "hindi": [
            'अत', 'अपना', 'अपनी', 'अपने', 'अभी', 'अंदर', 'आदि', 'आप', 'इत्यादि', 'इन', 'इनका', 'इन्हीं', 'इन्हें',
            'इन्हों', 'इस', 'इसका', 'इसकी', 'इसके', 'इसमें', 'इसी', 'इसे', 'उन', 'उनका', 'उनकी', 'उनके', 'उनको',
            'उन्हीं', 'उन्हें', 'उन्हों', 'उस', 'उसके', 'उसी', 'उसे', 'एक', 'एवं', 'एस', 'ऐसे', 'और', 'कई', 'कर',
            'करता', 'करते', 'करना', 'करने', 'करें', 'कहते', 'कहा', 'का', 'काफ़ी', 'कि', 'कितना', 'किन्हें', 'किन्हों',
            'किया', 'किर', 'किस', 'किसी', 'किसे', 'की', 'कुछ', 'कुल', 'के', 'को', 'कोई', 'कौन', 'कौनसा', 'गया', 'घर',
            'जब', 'जहाँ', 'जा', 'जितना', 'जिन', 'जिन्हें', 'जिन्हों', 'जिस', 'जिसे', 'जीधर', 'जैसा', 'जैसे', 'जो', 'तक',
            'तब', 'तरह', 'तिन', 'तिन्हें', 'तिन्हों', 'तिस', 'तिसे', 'तो', 'तुम', 'तुम्हारा', 'था', 'थी', 'थे', 'दबारा',
            'दिया', 'दुसरा', 'दूसरे', 'दो', 'द्वारा', 'न', 'नके', 'नहीं', 'ना', 'निहायत', 'नीचे', 'ने', 'पर', 'पहले',
            'पूरा', 'पे', 'फिर', 'बनी', 'बही', 'बहुत', 'बाद', 'बाला', 'बिलकुल', 'भी', 'भीतर', 'मगर', 'मानो', 'मे',
            'में', 'मैं', 'यदि', 'यह', 'यहाँ', 'यही', 'या', 'यिह', 'ये', 'रखें', 'रहा', 'रहे', 'ऱ्वासा', 'लिए', 'लिये',
            'लेकिन', 'व', 'वग़ैरह', 'वर्ग', 'वह', 'वहाँ', 'वहीं', 'वाले', 'वुह', 'वे', 'सकता', 'सकते', 'सबसे', 'सभी',
            'साथ', 'साबुत', 'साभ', 'सारा', 'से', 'सो', 'संग', 'ही', 'हुआ', 'हुई', 'हुए', 'है', 'हैं', 'हो', 'होता',
            'होती', 'होते', 'होना', 'होने'
        ],
        "malaysian": [
            'ada', 'adakah', 'adakan', 'adalah', 'adanya', 'adapun', 'agak', 'agar', 'akan', 'aku', 'akulah', 'akupun',
            'al', 'alangkah', 'allah', 'amat', 'antara', 'antaramu', 'antaranya', 'apa', 'apa-apa', 'apabila', 'apakah',
            'apapun', 'atas', 'atasmu', 'atasnya', 'atau', 'ataukah', 'ataupun', 'bagaimana', 'bagaimanakah', 'bagi',
            'bagimu', 'baginya', 'bahawa', 'bahawasanya', 'bahkan', 'bahwa', 'banyak', 'banyaknya', 'barangsiapa',
            'bawah', 'beberapa', 'begitu', 'begitupun', 'belaka', 'belum', 'belumkah', 'berada', 'berapa', 'berikan',
            'beriman', 'berkenaan', 'berupa', 'beserta', 'biarpun', 'bila', 'bilakah', 'bilamana', 'bisa', 'boleh',
            'bukan', 'bukankah', 'bukanlah', 'dahulu', 'dalam', 'dalamnya', 'dan', 'dapat', 'dapati', 'dapatkah',
            'dapatlah', 'dari', 'daripada', 'daripadaku', 'daripadamu', 'daripadanya', 'demi', 'demikian',
            'demikianlah', 'dengan', 'dengannya', 'di', 'dia', 'dialah', 'didapat', 'didapati', 'dimanakah', 'engkau',
            'engkaukah', 'engkaulah', 'engkaupun', 'hai', 'hampir', 'hampir-hampir', 'hanya', 'hanyalah', 'hendak',
            'hendaklah', 'hingga', 'ia', 'iaitu', 'ialah', 'ianya', 'inginkah', 'ini', 'inikah', 'inilah', 'itu',
            'itukah', 'itulah', 'jadi', 'jangan', 'janganlah', 'jika', 'jikalau', 'jua', 'juapun', 'juga', 'kalau',
            'kami', 'kamikah', 'kamipun', 'kamu', 'kamukah', 'kamupun', 'katakan', 'ke', 'kecuali', 'kelak', 'kembali',
            'kemudian', 'kepada', 'kepadaku', 'kepadakulah', 'kepadamu', 'kepadanya', 'kepadanyalah', 'kerana',
            'kerananya', 'kesan', 'ketika', 'kini', 'kita', 'ku', 'kurang', 'lagi', 'lain', 'lalu', 'lamanya',
            'langsung', 'lebih', 'maha', 'mahu', 'mahukah', 'mahupun', 'maka', 'malah', 'mana', 'manakah', 'manapun',
            'masih', 'masing', 'masing-masing', 'melainkan', 'memang', 'mempunyai', 'mendapat', 'mendapati',
            'mendapatkan', 'mengadakan', 'mengapa', 'mengapakah', 'mengenai', 'menjadi', 'menyebabkan',
            'menyebabkannya', 'mereka', 'merekalah', 'merekapun', 'meskipun', 'mu', 'nescaya', 'niscaya', 'nya', 'olah',
            'oleh', 'orang', 'pada', 'padahal', 'padamu', 'padanya', 'paling', 'para', 'pasti', 'patut', 'patutkah',
            'per', 'pergilah', 'perkara', 'perkaranya', 'perlu', 'pernah', 'pertama', 'pula', 'pun', 'sahaja', 'saja',
            'saling', 'sama', 'sama-sama', 'samakah', 'sambil', 'sampai', 'sana', 'sangat', 'sangatlah', 'saya', 'se',
            'seandainya', 'sebab', 'sebagai', 'sebagaimana', 'sebanyak', 'sebelum', 'sebelummu', 'sebelumnya',
            'sebenarnya', 'secara', 'sedang', 'sedangkan', 'sedikit', 'sedikitpun', 'segala', 'sehingga', 'sejak',
            'sekalian', 'sekalipun', 'sekarang', 'sekitar', 'selain', 'selalu', 'selama', 'selama-lamanya', 'seluruh',
            'seluruhnya', 'sementara', 'semua', 'semuanya', 'semula', 'senantiasa', 'sendiri', 'sentiasa', 'seolah',
            'seolah-olah', 'seorangpun', 'separuh', 'sepatutnya', 'seperti', 'seraya', 'sering', 'serta', 'seseorang',
            'sesiapa', 'sesuatu', 'sesudah', 'sesudahnya', 'sesungguhnya', 'sesungguhnyakah', 'setelah', 'setiap',
            'siapa', 'siapakah', 'sini', 'situ', 'situlah', 'suatu', 'sudah', 'sudahkah', 'sungguh', 'sungguhpun',
            'supaya', 'tadinya', 'tahukah', 'tak', 'tanpa', 'tanya', 'tanyakanlah', 'tapi', 'telah', 'tentang', 'tentu',
            'terdapat', 'terhadap', 'terhadapmu', 'termasuk', 'terpaksa', 'tertentu', 'tetapi', 'tiada', 'tiadakah',
            'tiadalah', 'tiap', 'tiap-tiap', 'tidak', 'tidakkah', 'tidaklah', 'turut', 'untuk', 'untukmu', 'wahai',
            'walau', 'walaupun', 'ya', 'yaini', 'yaitu', 'yakni', 'yang'
        ]
    }
    return stopwords.get(language, ['brrr'])
